/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppMeRouteImport } from './routes/_app.me'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSecurityRouteImport } from './routes/_app.security'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth.verify-otp'
import { Route as AppAnalysesIndexRouteImport } from './routes/_app.analyses.index'
import { Route as AppJobsIndexRouteImport } from './routes/_app.jobs.index'
import { Route as AppJobsIdRouteImport } from './routes/_app.jobs.$id'
import { Route as AppJobsNewRouteImport } from './routes/_app.jobs.new'
import { Route as AppResumesIndexRouteImport } from './routes/_app.resumes.index'
import { Route as AppResumesIdRouteImport } from './routes/_app.resumes.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AppAnalysesIndexRoute = AppAnalysesIndexRouteImport.update({
  id: '/analyses/',
  path: '/analyses/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsNewRoute = AppJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesIndexRoute = AppResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesIdRoute = AppResumesIdRouteImport.update({
  id: '/resumes/$id',
  path: '/resumes/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRoute
  '/billing': typeof AppBillingRoute
  '/me': typeof AppMeRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/security': typeof AppSecurityRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/resumes/$id': typeof AppResumesIdRoute
  '/analyses/': typeof AppAnalysesIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/resumes/': typeof AppResumesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRoute
  '/billing': typeof AppBillingRoute
  '/me': typeof AppMeRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/security': typeof AppSecurityRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/jobs/$id': typeof AppJobsIdRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/resumes/$id': typeof AppResumesIdRoute
  '/analyses': typeof AppAnalysesIndexRoute
  '/jobs': typeof AppJobsIndexRoute
  '/resumes': typeof AppResumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/me': typeof AppMeRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/security': typeof AppSecurityRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/jobs/$id': typeof AppJobsIdRoute
  '/_app/jobs/new': typeof AppJobsNewRoute
  '/_app/resumes/$id': typeof AppResumesIdRoute
  '/_app/analyses/': typeof AppAnalysesIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/resumes/': typeof AppResumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/billing'
    | '/me'
    | '/notifications'
    | '/profile'
    | '/security'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-otp'
    | '/jobs/$id'
    | '/jobs/new'
    | '/resumes/$id'
    | '/analyses/'
    | '/jobs/'
    | '/resumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/billing'
    | '/me'
    | '/notifications'
    | '/profile'
    | '/security'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-otp'
    | '/jobs/$id'
    | '/jobs/new'
    | '/resumes/$id'
    | '/analyses'
    | '/jobs'
    | '/resumes'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/account'
    | '/_app/billing'
    | '/_app/me'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/security'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-otp'
    | '/_app/'
    | '/_app/jobs/$id'
    | '/_app/jobs/new'
    | '/_app/resumes/$id'
    | '/_app/analyses/'
    | '/_app/jobs/'
    | '/_app/resumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/analyses/': {
      id: '/_app/analyses/'
      path: '/analyses'
      fullPath: '/analyses/'
      preLoaderRoute: typeof AppAnalysesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$id': {
      id: '/_app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/new': {
      id: '/_app/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AppJobsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/': {
      id: '/_app/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof AppResumesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes/$id': {
      id: '/_app/resumes/$id'
      path: '/resumes/$id'
      fullPath: '/resumes/$id'
      preLoaderRoute: typeof AppResumesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppBillingRoute: typeof AppBillingRoute
  AppMeRoute: typeof AppMeRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppIndexRoute: typeof AppIndexRoute
  AppJobsIdRoute: typeof AppJobsIdRoute
  AppJobsNewRoute: typeof AppJobsNewRoute
  AppResumesIdRoute: typeof AppResumesIdRoute
  AppAnalysesIndexRoute: typeof AppAnalysesIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppResumesIndexRoute: typeof AppResumesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppBillingRoute: AppBillingRoute,
  AppMeRoute: AppMeRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppIndexRoute: AppIndexRoute,
  AppJobsIdRoute: AppJobsIdRoute,
  AppJobsNewRoute: AppJobsNewRoute,
  AppResumesIdRoute: AppResumesIdRoute,
  AppAnalysesIndexRoute: AppAnalysesIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppResumesIndexRoute: AppResumesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
